[package]
name = "cosmic-ext-whether"
version = "0.6.0"
edition = "2021"
license = "GPL-3.0-only"
description = "Weather applet for COSMIC panel"
repository = "https://github.com/nwxnw/cosmic-ext-whether"

[dependencies]
i18n-embed = { version = "0.16", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.10"
rust-embed = "8"
reqwest = { version = "0.13", features = ["json", "query"] }
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
weathervane = "0.13.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["applet", "applet-token", "dbus-config", "multi-window", "tokio", "wayland"]
